apiVersion: apps/v1
kind: Deployment
metadata:
  name: cts-deploy
  labels:
    app: cts-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cts-api
  template:
    metadata:
      labels:
        app: cts-api
    spec:
      containers:
      - name: cts-api
        image: charisma03/cts-api:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
          - name: ASPNETCORE_URLS
            value: http://+:80
      imagePullSecrets:
      - name: myregistrykey